// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgd5UG2dgVR1lfg-y5eEXRVRJgAU0udKk',
    appId: '1:745790458947:web:cd218cfcc6db9db48018f6',
    messagingSenderId: '745790458947',
    projectId: 'projektgrupowy-ba8f2',
    authDomain: 'projektgrupowy-ba8f2.firebaseapp.com',
    storageBucket: 'projektgrupowy-ba8f2.firebasestorage.app',
    measurementId: 'G-NQG4XVYZ78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjsRU9PLEH88A-RIu-Vh8vDuH_RK41zxU',
    appId: '1:745790458947:android:562d51a25468f52a8018f6',
    messagingSenderId: '745790458947',
    projectId: 'projektgrupowy-ba8f2',
    storageBucket: 'projektgrupowy-ba8f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCDDoF8m9Si3F8IMiLFahQzWgVCnmRowg',
    appId: '1:745790458947:ios:2fc29a56f15d0b418018f6',
    messagingSenderId: '745790458947',
    projectId: 'projektgrupowy-ba8f2',
    storageBucket: 'projektgrupowy-ba8f2.firebasestorage.app',
    iosBundleId: 'com.example.projektGrupowy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCDDoF8m9Si3F8IMiLFahQzWgVCnmRowg',
    appId: '1:745790458947:ios:2fc29a56f15d0b418018f6',
    messagingSenderId: '745790458947',
    projectId: 'projektgrupowy-ba8f2',
    storageBucket: 'projektgrupowy-ba8f2.firebasestorage.app',
    iosBundleId: 'com.example.projektGrupowy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgd5UG2dgVR1lfg-y5eEXRVRJgAU0udKk',
    appId: '1:745790458947:web:7a4c8ef33b6ad2508018f6',
    messagingSenderId: '745790458947',
    projectId: 'projektgrupowy-ba8f2',
    authDomain: 'projektgrupowy-ba8f2.firebaseapp.com',
    storageBucket: 'projektgrupowy-ba8f2.firebasestorage.app',
    measurementId: 'G-RC4MXVJHE5',
  );

}